### ISSUE TITLE
CI build fails after merge to master

### ISSUE THREAD

**Issue by mbhoek** [solidtoken/SpecFlow.DependencyInjection#18]
After merging PR #17 into `master`, the [automated CI build failed](https://dev.azure.com/SolidToken/GitHub/_build/results?buildId=291).
```
error CS0246: The type or namespace name 'SolidToken_SpecFlow_DependencyInjection_Tests_XUnitAssemblyFixture' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\SpecFlow.DependencyInjection.Tests\SpecFlow.DependencyInjection.Tests.csproj]
```
However, on the same `master` branch a [manual build succeeds](https://dev.azure.com/SolidToken/GitHub/_build/results?buildId=292). 
The [pull request build also succeeded](https://dev.azure.com/SolidToken/GitHub/_build/results?buildId=290).

Is this a repeatable bug? What causes it? Is it solved by moving to GitHub Actions (#11)?

**Comment by mbhoek** [comment]
Probably related to SpecFlowOSS/SpecFlow#1825 (but does that explain it happening in the CI environment as well?). If it is a problem in SpecFlow, then moving to GitHub Actions won't solve it.

Downgrading to SpecFlow 3.0.225 results in a different error (note it still has something to do with the fixture):
```
    System.AggregateException : One or more errors occurred. (Value cannot be null. (Parameter 'key')) (The following constructor parameters did not have matching fixture data: FixtureData fixtureData)
    ---- System.ArgumentNullException : Value cannot be null. (Parameter 'key')
    ---- The following constructor parameters did not have matching fixture data: FixtureData fixtureData
```
